---
title: "R Notebook"
output: 
html_notebook: default
---

### Degree distribution

```{r}
rm(list=ls())
library(networkdata)
library(intergraph)
library(network)
library(igraph)
library(ergm)

# Load data
data(protein)
protein = simplify(protein, remove.multiple = TRUE)
```

```{r}
# Select vertices with different lethality name
others = which(!(igraph::vertex_attr(protein, "lethality") %in% c("Unknown", "Lethal", "Non-Lethal")))

# Set selected vertice attributes to "Other"
protein = set_vertex_attr(protein, "lethality", others, "Other")

# Save a network object of protein dataset as well
protein_net = asNetwork(protein)
summary(protein_net, print.adj = FALSE)
```

```{r, warnings = FALSE}
ergm.fit = ergm(protein_net ~ edges + nodematch("lethality", diff=T))
summary(ergm.fit)
```

```{r}
plogis(ergm.fit$coef[1])
```

```{r, warning = FALSE}
gof.model = gof(ergm.fit)
plot(gof.model)
```

```{r, warning = FALSE}
ergm.fit.2 = ergm(protein_net ~ nodefactor("lethality") + concurrent + edges)
summary(ergm.fit.2)
```

```{r}
ergm.fit.3 = ergm(protein_net ~ nodefactor("lethality") + concurrent + edges + nodematch("lethality", diff = F))
summary(ergm.fit.3)
```

